project_id = "yucwxukikfianvaokebs"

[functions.import-toolkit-cards]
verify_jwt = false

[functions.ai-reflection]
verify_jwt = false

[functions.ai-deliverables]
verify_jwt = false

[functions.ai-coach]
verify_jwt = false

[functions.analyze-challenge]
verify_jwt = false
