import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Phase assignment: cards 1-5 = foundations, 6-10 = model, 11-15 = growth, 16-20 = execution
function getPhase(index: number): string {
  if (index < 5) return "foundations";
  if (index < 10) return "model";
  if (index < 15) return "growth";
  return "execution";
}

// Pillar ID mapping
const PILLAR_IDS = {
  thinking: "b0000000-0000-0000-0000-000000000001",
  business: "b0000000-0000-0000-0000-000000000002",
  innovation: "b0000000-0000-0000-0000-000000000003",
  finance: "b0000000-0000-0000-0000-000000000004",
  indicators: "b0000000-0000-0000-0000-000000000005",
  building: "b0000000-0000-0000-0000-000000000006",
  managing: "b0000000-0000-0000-0000-000000000007",
  gouvernance: "b0000000-0000-0000-0000-000000000008",
  profitability: "b0000000-0000-0000-0000-000000000009",
  fundraising: "b0000000-0000-0000-0000-000000000010",
};

// Pillar updates (name, slug, icon_name, description)
const PILLAR_UPDATES = [
  { id: PILLAR_IDS.thinking, name: "Thinking", slug: "thinking", icon_name: "Brain", description: "La psychologie de l'entrepreneur : Curiosité, Pensée critique, Résilience.", sort_order: 0 },
  { id: PILLAR_IDS.innovation, name: "Innovation", slug: "innovation", icon_name: "Lightbulb", description: "Idéation, Design Thinking et Agilité.", sort_order: 1 },
  { id: PILLAR_IDS.business, name: "Business", slug: "business", icon_name: "Briefcase", description: "Modèle économique, Stratégie et Marché.", sort_order: 2 },
  { id: PILLAR_IDS.building, name: "Building", slug: "building", icon_name: "Hammer", description: "Les fondations techniques, juridiques et logistiques.", sort_order: 3 },
  { id: PILLAR_IDS.profitability, name: "Profitability", slug: "profitability", icon_name: "TrendingUp", description: "Rentabilité, Marges et Viabilité.", sort_order: 4 },
  { id: PILLAR_IDS.indicators, name: "Indicators", slug: "indicators", icon_name: "BarChart3", description: "KPIs, Métriques de succès et Tableaux de bord.", sort_order: 5 },
  { id: PILLAR_IDS.managing, name: "Managing", slug: "managing", icon_name: "Users", description: "Leadership, Culture d'équipe et Communication.", sort_order: 6 },
  { id: PILLAR_IDS.finance, name: "Finance", slug: "finance", icon_name: "Wallet", description: "Gestion de trésorerie, Contrôle des coûts.", sort_order: 7 },
  { id: PILLAR_IDS.gouvernance, name: "Gouvernance", slug: "gouvernance", icon_name: "Shield", description: "Structure légale, Conseil d'administration et Conformité.", sort_order: 8 },
  { id: PILLAR_IDS.fundraising, name: "Fundraising", slug: "fundraising", icon_name: "Heart", description: "Préparation à la levée de fonds.", sort_order: 9 },
];

// All 200 cards organized by pillar
const ALL_CARDS: Record<string, Array<{ title: string; definition: string; subtitle: string; action: string; kpi: string }>> = {
  // PAGE 3: INNOVATION
  innovation: [
    { title: "Idéation", definition: "Processus de génération d'idées nouvelles et créatives.", subtitle: "Base de l'innovation, permettant de développer des produits ou services uniques.", action: "Organisez des sessions de brainstorming pour produire un grand nombre d'idées sans jugement initial.", kpi: "Génère des idées nouvelles\nParticipe à des brainstormings\nEncourage la créativité des autres" },
    { title: "Collaboration", definition: "Travail conjoint pour atteindre un objectif commun.", subtitle: "Favorise le partage de connaissances et conduit à des solutions innovantes.", action: "Formez des équipes multidisciplinaires pour travailler sur le projet, favorisant l'échange d'idées et de compétences.", kpi: "Travaille en équipe\nPartage des connaissances\nConstruit sur les idées des autres" },
    { title: "Prototypage", definition: "Création d'une version initiale d'un produit pour le tester.", subtitle: "Permet de valider rapidement les idées et d'apporter des améliorations avant le lancement.", action: "Développez une version préliminaire de votre produit ou service pour tester ses fonctionnalités et son acceptation.", kpi: "Crée des maquettes\nTeste rapidement les concepts\nUtilise les feedbacks pour améliorer" },
    { title: "Amélioration Continue", definition: "Processus permanent d'optimisation des produits ou services.", subtitle: "Assure que l'entreprise reste compétitive en s'adaptant constamment.", action: "Mettez en place des processus pour recueillir régulièrement les retours et apporter des améliorations continues.", kpi: "Cherche à optimiser\nMesure les performances\nMet en place des processus d'amélioration" },
    { title: "Centré Utilisateur", definition: "Approche plaçant les besoins des utilisateurs au cœur du développement.", subtitle: "Garantit que les produits répondent réellement aux attentes des clients.", action: "Impliquez les utilisateurs finaux dans le processus de développement pour comprendre leurs besoins et préférences.", kpi: "Comprend les besoins clients\nImplique les utilisateurs\nCrée des solutions adaptées" },
    { title: "Disruption", definition: "Introduction d'innovations bouleversant le marché existant.", subtitle: "Offre un avantage concurrentiel significatif en changeant les règles du secteur.", action: "Identifiez les opportunités pour bouleverser les modèles existants en proposant des solutions radicalement nouvelles.", kpi: "Challenge les modèles existants\nPropose des solutions radicales\nImpacte le marché significativement" },
    { title: "Flexibilité", definition: "Capacité à s'adapter rapidement aux changements.", subtitle: "Essentielle pour innover et répondre aux évolutions du marché.", action: "Adaptez rapidement votre projet en fonction des retours, des tendances du marché ou des obstacles rencontrés.", kpi: "S'adapte rapidement\nChange de direction si nécessaire\nReste ouvert aux opportunités" },
    { title: "Co-création", definition: "Collaboration avec les parties prenantes pour créer de la valeur.", subtitle: "Renforce l'engagement des clients et améliore la pertinence des offres.", action: "Collaborez avec les clients, partenaires et autres parties prenantes pour développer ensemble votre offre.", kpi: "Implique les parties prenantes\nValorise les contributions externes\nDéveloppe des partenariats d'innovation" },
    { title: "Anticipation", definition: "Capacité à prévoir les évolutions futures du marché.", subtitle: "Permet de garder une longueur d'avance sur la concurrence.", action: "Surveillez les évolutions du marché, les innovations technologiques et les changements sociétaux.", kpi: "Suit les évolutions du marché\nPrédit les besoins futurs\nPrépare des solutions en avance" },
    { title: "Technologies Émergentes", definition: "Utilisation de nouvelles technologies pour innover.", subtitle: "Offre des possibilités de différenciation en intégrant des solutions avant-gardistes.", action: "Explorez l'application des nouvelles technologies (IA, IoT, blockchain, etc.) dans votre projet.", kpi: "Se tient informé des innovations technologiques\nExpérimente avec de nouvelles technologies\nIntègre les technologies dans les solutions" },
    { title: "Résolution de Problèmes", definition: "Aptitude à trouver des solutions efficaces aux défis.", subtitle: "Indispensable pour surmonter les obstacles et améliorer l'offre de l'entreprise.", action: "Appliquez des méthodes structurées (design thinking, méthodes agiles) pour trouver des solutions aux défis rencontrés.", kpi: "Identifie les obstacles\nPropose des solutions créatives\nRésout les problèmes complexes" },
    { title: "Partenariats", definition: "Relations collaboratives avec d'autres organisations.", subtitle: "Permet de combiner des ressources pour innover plus rapidement.", action: "Identifiez et collaborez avec des partenaires complémentaires pour renforcer votre proposition de valeur.", kpi: "Crée des alliances stratégiques\nCollabore avec d'autres entreprises\nPartage les ressources et les risques" },
    { title: "Design Thinking", definition: "Méthodologie centrée sur l'humain pour résoudre des problèmes.", subtitle: "Facilite la création de solutions qui répondent aux besoins des utilisateurs.", action: "Adoptez une approche centrée sur l'humain pour résoudre les problèmes et concevoir des solutions innovantes.", kpi: "Utilise une approche centrée sur l'humain\nSuit les étapes de l'empathie à la mise en œuvre\nFavorise l'innovation par la créativité structurée" },
    { title: "Prise de Risques", definition: "Disposition à entreprendre des actions malgré l'incertitude.", subtitle: "Essentielle pour innover et se démarquer sur le marché.", action: "Osez sortir de votre zone de confort en expérimentant de nouvelles idées, tout en évaluant les risques associés.", kpi: "N'a pas peur de l'échec\nExpérimente de nouvelles idées\nInvestit dans des projets innovants" },
    { title: "Brainstorming", definition: "Technique pour générer un grand nombre d'idées en groupe.", subtitle: "Stimule la créativité collective et peut conduire à des solutions inattendues.", action: "Encouragez l'équipe à partager librement des idées sans jugement pour résoudre un problème spécifique.", kpi: "Organise des sessions d'idées\nEncourage la participation\nGénère un grand nombre de propositions" },
    { title: "Processus Innovants", definition: "Mise en place de nouvelles méthodes pour améliorer les opérations.", subtitle: "Augmente l'efficacité et la compétitivité de l'entreprise.", action: "Revoyez et améliorez vos processus internes pour favoriser l'innovation (méthodes agiles, lean startup, etc.).", kpi: "Met en place des méthodes nouvelles\nOptimise les processus existants\nCrée des flux de travail plus efficaces" },
    { title: "Systèmes de Pensée", definition: "Approche globale considérant les interrelations dans un système.", subtitle: "Aide à comprendre la complexité des entreprises et des marchés.", action: "Considérez les interrelations entre les différents éléments de votre projet et leur impact sur l'ensemble.", kpi: "Voit les relations entre les éléments\nComprend les impacts à long terme\nGère la complexité" },
    { title: "Passion", definition: "Enthousiasme intense pour son travail ou projet.", subtitle: "Motive l'entrepreneur à persévérer et inspire l'équipe.", action: "Identifiez ce qui vous motive profondément dans votre projet et partagez cette passion avec votre équipe.", kpi: "Montre de l'enthousiasme\nInspire les autres\nS'engage pleinement dans les projets" },
    { title: "Agilité", definition: "Capacité à réagir rapidement aux changements.", subtitle: "Permet de s'adapter aux évolutions du marché et de saisir les opportunités.", action: "Adoptez des méthodes de travail agiles pour réagir rapidement aux changements et aux feedbacks.", kpi: "Réagit rapidement aux changements\nPriorise les tâches\nUtilise des méthodes agiles de gestion de projet" },
    { title: "Pensée Disruptive", definition: "Capacité à envisager des solutions radicalement nouvelles.", subtitle: "Peut conduire à des innovations majeures offrant un avantage concurrentiel.", action: "Challengez les paradigmes actuels en posant des questions telles que \"Et si... ?\" pour imaginer des scénarios innovants.", kpi: "Pense en dehors des sentiers battus\nRemet en question les paradigmes\nCrée des solutions inattendues" },
  ],

  // PAGE 4: THINKING
  thinking: [
    { title: "Curiosité", definition: "Désir d'apprendre et de découvrir de nouvelles choses.", subtitle: "Stimule l'innovation et permet de découvrir de nouvelles opportunités sur le marché.", action: "Explorez votre environnement, le marché, les tendances et les besoins non satisfaits. Lisez, assistez à des conférences, engagez des discussions.", kpi: "POSE DES QUESTIONS\nRECHERCHE ACTIVEMENT DES INFORMATIONS\nPARTICIPE AUX DISCUSSIONS" },
    { title: "Pensée Critique", definition: "Capacité à analyser objectivement une situation ou une information.", subtitle: "Aide à prendre des décisions éclairées et à identifier les meilleures solutions aux problèmes.", action: "Évaluez objectivement les informations recueillies. Remettez en question les hypothèses, identifiez les biais, vérifiez la fiabilité des sources.", kpi: "ANALYSE LES INFORMATIONS\nREMET EN QUESTION LES IDÉES REÇUES\nIDENTIFIE LES BIAIS" },
    { title: "Observation", definition: "Action de regarder attentivement pour recueillir des informations.", subtitle: "Permet de comprendre le marché et les besoins des clients pour adapter son offre efficacement.", action: "Étudiez les comportements, habitudes et besoins de votre public cible. Utilisez l'observation terrain et l'analyse des données clients.", kpi: "NOTE LES DÉTAILS\nREPÈRE LES TENDANCES\nCOMPREND LE CONTEXTE" },
    { title: "Analyse", definition: "Examen détaillé des éléments d'un problème pour en comprendre la structure.", subtitle: "Facilite la résolution de problèmes complexes et l'élaboration de stratégies efficaces.", action: "Utilisez des outils analytiques pour segmenter le marché, évaluer la concurrence, identifier les tendances clés.", kpi: "DÉCOMPOSE LES PROBLÈMES\nÉVALUE LES SOLUTIONS\nUTILISE DES DONNÉES POUR DÉCIDER" },
    { title: "Questionnement", definition: "Pratique de poser des questions pour approfondir la compréhension.", subtitle: "Encourage la remise en question des idées préconçues et stimule l'innovation.", action: "Challengez votre projet en vous posant des questions fondamentales sur le problème résolu, la proposition de valeur, etc.", kpi: "EXPLORE LES \"POURQUOI\"\nCHALLENGE LES SUPPOSITIONS\nSTIMULE LA RÉFLEXION DES AUTRES" },
    { title: "Adaptabilité", definition: "Capacité à s'ajuster rapidement aux changements.", subtitle: "Essentielle pour naviguer dans un environnement entrepreneurial en constante évolution.", action: "Restez ouvert aux changements et prêt à ajuster votre projet selon les retours et les évolutions du marché.", kpi: "S'AJUSTE AUX CHANGEMENTS\nACCEPTE LA NOUVEAUTÉ\nMODIFIE SES PLANS SI NÉCESSAIRE" },
    { title: "Réflexion", definition: "Action de penser profondément à ses expériences pour en tirer des leçons.", subtitle: "Permet d'apprendre de ses erreurs et d'améliorer continuellement ses approches.", action: "Analysez vos expériences pour en tirer des leçons. Utilisez un journal de bord ou des sessions de réflexion personnelle.", kpi: "PREND DU RECUL\nÉVALUE SES ACTIONS\nAPPREND DE L'EXPÉRIENCE" },
    { title: "Synthèse", definition: "Capacité à combiner différentes idées pour former une vision cohérente.", subtitle: "Aide à créer des stratégies globales en intégrant diverses informations.", action: "Regroupez les données collectées pour élaborer une vision cohérente. Créez des modèles ou schémas pour visualiser les connexions.", kpi: "COMBINE DES IDÉES\nVOIT LES LIENS ENTRE LES CONCEPTS\nPROPOSE DES SOLUTIONS INTÉGRÉES" },
    { title: "Objectivité", definition: "Jugement impartial non influencé par des préjugés.", subtitle: "Garantit des décisions basées sur des faits, réduisant les risques d'erreurs stratégiques.", action: "Mettez de côté vos émotions pour évaluer votre projet impartialement. Sollicitez des avis externes pour plus d'objectivité.", kpi: "ÉVALUE SANS PRÉJUGÉS\nPREND DES DÉCISIONS IMPARTIALES\nÉCOUTE TOUS LES POINTS DE VUE" },
    { title: "Pensée Latérale", definition: "Approche créative pour résoudre des problèmes de manière indirecte.", subtitle: "Encourage l'innovation en trouvant des solutions non conventionnelles.", action: "Utilisez des techniques comme le brainstorming, le mind mapping pour générer des idées innovantes.", kpi: "UTILISE DES APPROCHES NON CONVENTIONNELLES\nTROUVE DES ALTERNATIVES\nRÉSOUT LES PROBLÈMES DE MANIÈRE CRÉATIVE" },
    { title: "Empathie", definition: "Capacité à comprendre les sentiments des autres.", subtitle: "Favorise de meilleures relations avec les clients et l'équipe, améliorant la satisfaction et la collaboration.", action: "Adoptez la perspective de vos clients pour comprendre leurs besoins. Menez des interviews ou focus groups.", kpi: "COMPREND LES ÉMOTIONS DES AUTRES\nADAPTE SA COMMUNICATION\nCRÉE DES RELATIONS POSITIVES" },
    { title: "Intuition", definition: "Connaissance immédiate sans recourir au raisonnement conscient.", subtitle: "Aide à prendre des décisions rapides lorsque les données sont insuffisantes.", action: "Écoutez votre intuition lors de décisions difficiles, tout en la confrontant aux données disponibles.", kpi: "FAIT CONFIANCE À SON INSTINCT\nPREND DES DÉCISIONS RAPIDES\nIDENTIFIE DES OPPORTUNITÉS ÉMERGENTES" },
    { title: "Apprentissage Continu", definition: "Engagement permanent dans le développement de nouvelles compétences.", subtitle: "Assure que l'entrepreneur reste compétitif et à jour sur les tendances du marché.", action: "Suivez des formations, lisez, participez à des webinaires pour enrichir vos compétences.", kpi: "SE FORME RÉGULIÈREMENT\nCHERCHE À S'AMÉLIORER\nINTÈGRE DE NOUVELLES COMPÉTENCES" },
    { title: "Vision Stratégique", definition: "Capacité à définir une direction claire pour l'avenir.", subtitle: "Guide l'entreprise vers des objectifs à long terme et oriente les décisions quotidiennes.", action: "Élaborez une vision claire de l'avenir de votre entreprise, fixez des objectifs à long terme et les étapes pour y parvenir.", kpi: "DÉFINIT DES OBJECTIFS CLAIRS\nANTICIPE LES TENDANCES\nALIGNE LES ACTIONS SUR LA VISION" },
    { title: "Esprit Ouvert", definition: "Disposition à considérer de nouvelles idées sans préjugés.", subtitle: "Facilite l'adaptation et l'innovation en acceptant le changement.", action: "Soyez réceptif aux feedbacks, suggestions et critiques constructives. Explorez des perspectives différentes.", kpi: "ACCEPTE LES IDÉES NOUVELLES\nEXPLORE DES PERSPECTIVES DIFFÉRENTES\nÉVITE LES JUGEMENTS HÂTIFS" },
    { title: "Écoute Active", definition: "Technique de communication impliquant une écoute attentive.", subtitle: "Améliore la compréhension des besoins des clients et favorise des relations solides.", action: "Lors des interactions, écoutez attentivement et posez des questions pour clarifier.", kpi: "CONCENTRE SON ATTENTION\nCOMPREND RÉELLEMENT L'INTERLOCUTEUR\nPOSE DES QUESTIONS POUR CLARIFIER" },
    { title: "Gestion du Temps", definition: "Capacité à planifier et organiser son temps efficacement.", subtitle: "Essentielle pour gérer les multiples tâches et respecter les délais dans un projet entrepreneurial.", action: "Priorisez vos tâches, établissez des plannings, évitez la procrastination. Utilisez des outils de gestion du temps.", kpi: "PRIORISE LES TÂCHES\nRESPECTE LES DÉLAIS\nPLANIFIE EFFICACEMENT" },
    { title: "Prise de Décision", definition: "Processus de choisir une option parmi plusieurs.", subtitle: "Permet d'avancer rapidement et d'orienter l'entreprise vers ses objectifs.", action: "Évaluez les options en considérant avantages, risques, impacts. Prenez des décisions et assumez-les.", kpi: "ÉVALUE LES OPTIONS\nASSUME LES CHOIX\nAGIT DE MANIÈRE DÉCISIVE" },
    { title: "Conscience Globale", definition: "Compréhension des enjeux internationaux et culturels.", subtitle: "Ouvre des opportunités sur les marchés internationaux et favorise une vision globale.", action: "Informez-vous sur les tendances mondiales, différences culturelles, opportunités internationales.", kpi: "COMPREND LES ENJEUX MONDIAUX\nINTÈGRE LA DIVERSITÉ CULTURELLE\nPENSE À L'IMPACT SOCIÉTAL" },
    { title: "Auto-Évaluation", definition: "Pratique de s'examiner pour identifier ses forces et faiblesses.", subtitle: "Encourage le développement personnel et professionnel, améliorant la performance de l'entrepreneur.", action: "Faites régulièrement le point sur vos compétences, réalisations, domaines à améliorer. Fixez des objectifs de développement personnel.", kpi: "IDENTIFIE SES FORCES ET FAIBLESSES\nRECHERCHE LE FEEDBACK\nS'ENGAGE DANS LE DÉVELOPPEMENT PERSONNEL" },
  ],

  // PAGE 5: BUSINESS
  business: [
    { title: "Analyse de Marché", definition: "Étude des caractéristiques d'un marché pour en comprendre le fonctionnement.", subtitle: "Comprendre le contexte dans lequel vous allez opérer pour élaborer une stratégie adaptée.", action: "Collectez des données sur le marché cible, la concurrence, les tendances et les segments de clients.", kpi: "CONNAÎT LE MARCHÉ CIBLE\nIDENTIFIE LES TENDANCES\nÉVALUE LA CONCURRENCE" },
    { title: "Segmentation Clientèle", definition: "Division du marché en groupes de clients aux besoins similaires.", subtitle: "Personnaliser votre offre et vos actions marketing pour chaque segment.", action: "Divisez le marché en groupes de clients ayant des besoins ou comportements similaires.", kpi: "CATÉGORISE LES CLIENTS\nADAPTE L'OFFRE À CHAQUE SEGMENT\nCOMPREND LES BESOINS SPÉCIFIQUES" },
    { title: "Modèle Économique", definition: "Schéma décrivant comment l'entreprise crée et capture de la valeur.", subtitle: "Assurer la viabilité financière et la rentabilité de votre projet.", action: "Établissez comment votre entreprise va créer, délivrer et capturer de la valeur (sources de revenus, structure de coûts, etc.).", kpi: "DÉFINIT LES SOURCES DE REVENUS\nÉTABLIT LA STRUCTURE DES COÛTS\nCONÇOIT LE MODÈLE DE RENTABILITÉ" },
    { title: "Stratégie de Croissance", definition: "Planification des actions pour développer l'entreprise.", subtitle: "Orienter vos efforts vers des objectifs clairs d'expansion et de développement.", action: "Planifiez les actions pour développer votre entreprise (expansion géographique, diversification, partenariats, etc.).", kpi: "FIXE DES OBJECTIFS DE DÉVELOPPEMENT\nPLANIFIE L'EXPANSION\nDIVERSIFIE LES ACTIVITÉS" },
    { title: "Marketing", definition: "Actions visant à promouvoir les produits ou services.", subtitle: "Attirer et fidéliser les clients, augmenter la notoriété de la marque.", action: "Concevez des actions pour promouvoir vos produits ou services (mix marketing, canaux de communication, positionnement).", kpi: "COMMUNIQUE EFFICACEMENT\nGÈRE L'IMAGE DE MARQUE\nATTIRE DE NOUVEAUX CLIENTS" },
    { title: "Approche Client", definition: "Manière dont l'entreprise interagit avec ses clients.", subtitle: "Augmenter la satisfaction et la fidélité des clients, générer des recommandations positives.", action: "Mettez en place des processus pour assurer une excellente expérience client (service client, personnalisation, suivi).", kpi: "OFFRE UN EXCELLENT SERVICE\nFIDÉLISE LES CLIENTS\nENCOURAGE LES RECOMMANDATIONS" },
    { title: "Chaîne de Valeur", definition: "Série d'activités ajoutant de la valeur au produit ou service.", subtitle: "Réduire les coûts, augmenter l'efficacité et la qualité de votre offre.", action: "Analysez les activités qui ajoutent de la valeur à votre produit ou service pour identifier les améliorations possibles.", kpi: "OPTIMISE LES ACTIVITÉS CLÉS\nIDENTIFIE LES PARTENAIRES STRATÉGIQUES\nCRÉE DE LA VALEUR AJOUTÉE" },
    { title: "Investissement", definition: "Allocation de ressources financières pour un retour futur.", subtitle: "Assurer le financement adéquat pour le développement et la croissance de votre entreprise.", action: "Déterminez les ressources financières nécessaires et explorez les options de financement (capital-risque, prêts, subventions, etc.).", kpi: "GÈRE LES RESSOURCES FINANCIÈRES\nALLOUE LE CAPITAL EFFICACEMENT\nRECHERCHE DES FINANCEMENTS EXTERNES" },
    { title: "Gestion des Risques", definition: "Processus d'identification et de gestion des risques potentiels.", subtitle: "Réduire l'impact des événements négatifs sur votre entreprise.", action: "Identifiez les risques potentiels (financiers, opérationnels, juridiques) et élaborez des plans d'atténuation.", kpi: "IDENTIFIE LES RISQUES POTENTIELS\nMET EN PLACE DES PLANS D'ATTÉNUATION\nSUIT LES INDICATEURS DE RISQUE" },
    { title: "Internationalisation", definition: "Expansion des activités au-delà des frontières nationales.", subtitle: "Étendre votre marché potentiel et diversifier vos sources de revenus.", action: "Évaluez les opportunités et défis d'une expansion à l'étranger, adaptez votre offre aux marchés internationaux.", kpi: "ÉVALUE LES OPPORTUNITÉS À L'ÉTRANGER\nADAPTE L'OFFRE AUX MARCHÉS LOCAUX\nGÈRE LES OPÉRATIONS INTERNATIONALES" },
    { title: "Prix et Tarification", definition: "Détermination du montant facturé pour un produit ou service.", subtitle: "Optimiser les revenus tout en restant compétitif sur le marché.", action: "Établissez des prix en fonction de la valeur perçue, des coûts, de la concurrence et de la stratégie marketing.", kpi: "FIXE DES PRIX COMPÉTITIFS\nCOMPREND LA PERCEPTION DE LA VALEUR\nAJUSTE LES TARIFS SELON LE MARCHÉ" },
    { title: "Avantage Concurrentiel", definition: "Attribut permettant de surpasser les concurrents.", subtitle: "Attirer les clients en offrant une proposition de valeur unique.", action: "Déterminez ce qui différencie votre entreprise de la concurrence (innovation, qualité, service, coût).", kpi: "IDENTIFIE CE QUI DIFFÉRENCIE L'ENTREPRISE\nPROTÈGE LES INNOVATIONS\nEXPLOITE LES FORCES UNIQUES" },
    { title: "Conformité Légale", definition: "Respect des lois et réglementations applicables.", subtitle: "Éviter les sanctions légales et protéger la réputation de votre entreprise.", action: "Informez-vous sur les lois et réglementations applicables à votre activité et assurez-vous de les respecter.", kpi: "RESPECTE LES RÉGLEMENTATIONS\nASSURE LA CONFORMITÉ DES OPÉRATIONS\nGÈRE LES OBLIGATIONS LÉGALES" },
    { title: "Objectifs SMART", definition: "Objectifs Spécifiques, Mesurables, Atteignables, Réalistes, Temporellement définis.", subtitle: "Clarifier vos priorités et faciliter le suivi des progrès réalisés.", action: "Établissez des objectifs Spécifiques, Mesurables, Atteignables, Réalistes et Temporellement définis pour guider vos actions.", kpi: "DÉFINIT DES OBJECTIFS SPÉCIFIQUES\nMESURE LES PROGRÈS\nATTEINT LES RÉSULTATS ESCOMPTÉS" },
    { title: "Responsabilité Sociale", definition: "Engagement à agir de manière éthique et contribuer positivement à la société.", subtitle: "Améliorer l'image de marque et répondre aux attentes des clients et partenaires en matière de responsabilité sociale.", action: "Mettez en place des pratiques éthiques et durables, engagez-vous auprès de la communauté.", kpi: "AGIT DE MANIÈRE ÉTHIQUE\nCONTRIBUE À LA COMMUNAUTÉ\nINTÈGRE LE DÉVELOPPEMENT DURABLE" },
    { title: "Réseautage", definition: "Création de relations professionnelles pour des avantages mutuels.", subtitle: "Ouvrir des opportunités de partenariats, de clients potentiels et d'apprentissages.", action: "Participez à des événements, rejoignez des associations professionnelles, utilisez les réseaux sociaux pour établir des contacts.", kpi: "ÉTABLIT DES RELATIONS PROFESSIONNELLES\nPARTICIPE À DES ÉVÉNEMENTS\nDÉVELOPPE UN RÉSEAU SOLIDE" },
    { title: "Gestion Financière", definition: "Gestion des ressources financières pour atteindre les objectifs.", subtitle: "Assurer la stabilité financière et la rentabilité de votre entreprise.", action: "Élaborez des budgets, suivez les flux de trésorerie, analysez les performances financières régulièrement.", kpi: "GÈRE LES FLUX DE TRÉSORERIE\nÉLABORE DES BUDGETS\nOPTIMISE LES RESSOURCES FINANCIÈRES" },
    { title: "Rentabilité", definition: "Capacité à générer des bénéfices à partir des activités.", subtitle: "Prendre des décisions éclairées pour améliorer la performance financière.", action: "Calculez régulièrement vos marges bénéficiaires, retour sur investissement, seuil de rentabilité.", kpi: "GÉNÈRE DES PROFITS\nAMÉLIORE LES MARGES\nRÉDUIT LES COÛTS INUTILES" },
    { title: "Soutenabilité", definition: "Capacité à maintenir les activités sur le long terme.", subtitle: "Répondre aux préoccupations environnementales et sociales, réduire les coûts à long terme.", action: "Adoptez des pratiques respectueuses de l'environnement, gérez les ressources de manière responsable.", kpi: "ASSURE LA PÉRENNITÉ DE L'ENTREPRISE\nADOPTE DES PRATIQUES DURABLES\nPRÉPARE L'AVENIR" },
    { title: "Excellence Opérationnelle", definition: "Atteinte d'un haut niveau d'efficacité dans les opérations.", subtitle: "Augmenter la satisfaction client, réduire les coûts et renforcer la compétitivité.", action: "Optimisez les processus, améliorez la qualité, formez le personnel pour maximiser l'efficacité opérationnelle.", kpi: "OPTIMISE LES PROCESSUS\nAMÉLIORE LA QUALITÉ\nATTEINT L'EFFICACITÉ MAXIMALE" },
  ],

  // PAGE 6: BUILDING
  building: [
    { title: "Élément de Base", definition: "Composant fondamental nécessaire pour construire un produit ou service.", subtitle: "Assure des fondations solides pour le développement futur de l'entreprise ou du produit.", action: "Identifiez les composantes essentielles de votre projet (infrastructure, équipe, ressources clés).", kpi: "CONSTRUIT LES FONDATIONS\nÉTABLIT LES PREMIÈRES STRUCTURES\nPOSE LES BASES SOLIDES" },
    { title: "Planification", definition: "Processus d'élaboration de plans détaillés pour atteindre les objectifs.", subtitle: "Essentielle pour organiser les ressources et guider les actions vers le succès.", action: "Définissez les étapes, les échéances, les ressources nécessaires pour atteindre vos objectifs.", kpi: "DÉFINIT LES ÉTAPES CLÉS\nÉTABLIT UN CALENDRIER\nALLOUE LES RESSOURCES" },
    { title: "Sécurité", definition: "Mesures prises pour protéger les personnes et les biens des dangers.", subtitle: "Protège l'entreprise des pertes et assure le bien-être des employés, évitant des coûts supplémentaires.", action: "Mettez en place des protocoles pour protéger les personnes, les données et les actifs de l'entreprise.", kpi: "GARANTIT UN ENVIRONNEMENT SÛR\nRESPECTE LES NORMES DE SÉCURITÉ\nFORME LE PERSONNEL AUX BONNES PRATIQUES" },
    { title: "Compétences Techniques", definition: "Connaissances et aptitudes spécifiques nécessaires pour accomplir des tâches.", subtitle: "Assure que l'équipe peut développer et maintenir les produits ou services de qualité.", action: "Identifiez les compétences nécessaires, formez votre équipe ou recrutez des experts.", kpi: "DÉVELOPPE LES COMPÉTENCES NÉCESSAIRES\nRECRUTE DES EXPERTS\nFORME L'ÉQUIPE" },
    { title: "Processus Opérationnels", definition: "Méthodes et procédures pour réaliser les activités quotidiennes efficacement.", subtitle: "Améliorent l'efficacité et la cohérence des opérations, réduisant les erreurs et les coûts.", action: "Standardisez et documentez les procédures pour améliorer l'efficacité et réduire les erreurs.", kpi: "MET EN PLACE DES PROCÉDURES\nSTANDARDISE LES OPÉRATIONS\nDOCUMENTE LES PROCESSUS" },
    { title: "Développement", definition: "Processus d'amélioration ou de croissance des produits ou services.", subtitle: "Permet à l'entreprise de rester compétitive en innovant et en répondant aux besoins du marché.", action: "Encouragez l'apprentissage, l'innovation et l'amélioration au sein de l'équipe.", kpi: "FAIT ÉVOLUER LES PRODUITS\nAMÉLIORE LES SERVICES\nINCARNE L'INNOVATION CONTINUE" },
    { title: "Intégration", definition: "Combinaison de différents systèmes ou processus pour fonctionner ensemble.", subtitle: "Assure que toutes les parties de l'entreprise travaillent harmonieusement, améliorant l'efficacité globale.", action: "Faites en sorte que les différents systèmes et processus fonctionnent ensemble de manière cohérente.", kpi: "ASSURE LA COHÉRENCE ENTRE LES DÉPARTEMENTS\nFACILITE LA COMMUNICATION INTERNE\nUNIFIE LES EFFORTS" },
    { title: "Travail d'Équipe", definition: "Collaboration entre les membres pour atteindre un objectif commun.", subtitle: "Augmente la productivité et la créativité, conduisant à de meilleurs résultats.", action: "Promouvez la collaboration, la communication ouverte et la confiance au sein de l'équipe.", kpi: "FAVORISE LA COLLABORATION\nENCOURAGE L'ESPRIT D'ÉQUIPE\nRÉSOUT LES CONFLITS" },
    { title: "Ressources", definition: "Actifs matériels, humains et financiers nécessaires aux activités.", subtitle: "Une gestion efficace optimise les opérations et réduit les coûts, essentiel pour la viabilité de l'entreprise.", action: "Allouez judicieusement les ressources humaines, matérielles et financières en fonction des priorités.", kpi: "IDENTIFIE LES BESOINS MATÉRIELS\nGÈRE LES STOCKS\nOPTIMISE L'UTILISATION DES RESSOURCES" },
    { title: "Fiabilité", definition: "Capacité à fournir des résultats constants et de qualité.", subtitle: "Renforce la confiance des clients et partenaires, favorisant la fidélisation et la réputation.", action: "Maintenez des standards élevés de qualité et de cohérence dans les produits ou services offerts.", kpi: "ASSURE LA QUALITÉ CONSTANTE\nRESPECTE LES ENGAGEMENTS\nÉTABLIT LA CONFIANCE DES CLIENTS" },
    { title: "Évolution", definition: "Processus de changement et de développement progressif dans le temps.", subtitle: "Permet de s'adapter aux nouvelles conditions du marché et de rester compétitif.", action: "Anticipez les besoins futurs, les tendances technologiques, les changements du marché pour adapter votre projet.", kpi: "ADAPTE LES STRUCTURES\nGÈRE LA CROISSANCE\nPRÉPARE L'EXPANSION FUTURE" },
    { title: "Maintenance", definition: "Actions visant à préserver les équipements en bon état.", subtitle: "Assure la continuité des opérations et prolonge la durée de vie des actifs, réduisant les coûts à long terme.", action: "Établissez des programmes d'entretien régulier pour les équipements, les systèmes, les infrastructures.", kpi: "ENTRETIENT LES ÉQUIPEMENTS\nPRÉVOIT LES RÉPARATIONS\nMINIMISE LES INTERRUPTIONS" },
    { title: "Optimisation", definition: "Amélioration pour rendre quelque chose aussi efficace que possible.", subtitle: "Augmente l'efficacité opérationnelle, réduit les coûts et améliore la qualité.", action: "Identifiez les domaines d'amélioration, éliminez les gaspillages, implémentez des solutions plus efficaces.", kpi: "ANALYSE LES PERFORMANCES\nAMÉLIORE L'EFFICACITÉ\nRÉDUIT LES GASPILLAGES" },
    { title: "Contrôle Qualité", definition: "Activités pour vérifier que les produits répondent aux standards.", subtitle: "Garantit la satisfaction client, réduit les défauts et les retours, améliorant la réputation.", action: "Définissez des standards de qualité, mettez en place des procédures de vérification et de correction.", kpi: "VÉRIFIE LES LIVRABLES\nRESPECTE LES STANDARDS\nCORRIGE LES ERREURS" },
    { title: "Lancement", definition: "Introduction d'un nouveau produit ou service sur le marché.", subtitle: "Moment crucial pour générer de l'intérêt, attirer les clients et établir la position sur le marché.", action: "Planifiez le lancement (marketing, logistique, support client), formez l'équipe, assurez-vous que tout est prêt.", kpi: "PRÉPARE LE MARCHÉ\nCOORDONNE LES ÉQUIPES\nEXÉCUTE LE PLAN AVEC SUCCÈS" },
    { title: "Relations Fournisseurs", definition: "Gestion des interactions avec les fournisseurs pour assurer l'approvisionnement.", subtitle: "Influence la qualité des produits, les coûts et la capacité à répondre à la demande.", action: "Sélectionnez des fournisseurs fiables, négociez les contrats, entretenez des relations positives.", kpi: "SÉLECTIONNE DES PARTENAIRES FIABLES\nNÉGOCIE LES CONTRATS\nGÈRE LES RELATIONS DURABLES" },
    { title: "Gestion de Projet", definition: "Application de méthodes pour planifier et finaliser les projets avec succès.", subtitle: "Assure que les projets sont terminés dans les délais et budgets, optimisant les ressources.", action: "Utilisez des outils et techniques (diagramme de Gantt, Scrum, etc.) pour planifier, exécuter et contrôler les projets.", kpi: "SUIT LES INDICATEURS CLÉS\nAJUSTE LES PLANS\nLIVRE LES PROJETS DANS LES DÉLAIS" },
    { title: "Cycle de Vie", definition: "Phases qu'un produit traverse de son introduction à son retrait du marché.", subtitle: "Aide à planifier les mises à jour, le marketing et la gestion des ressources.", action: "Gérez les différentes phases (développement, croissance, maturité, déclin) et adaptez les stratégies en conséquence.", kpi: "COMPREND LES PHASES DU PRODUIT\nPLANIFIE LES MISES À JOUR\nPRÉPARE LE REMPLACEMENT" },
    { title: "Orientation", definition: "Capacité à diriger l'équipe vers les objectifs fixés.", subtitle: "Fournit une direction claire, motive l'équipe et aligne les efforts sur la vision stratégique.", action: "Communiquez la vision, les objectifs et les attentes à l'équipe pour aligner les efforts.", kpi: "GUIDE L'ÉQUIPE\nCLARIFIE LES OBJECTIFS\nMAINTIENT LE CAP" },
    { title: "Résolution de Projets Complexes", definition: "Gestion efficace de projets présentant des défis importants.", subtitle: "Permet de surmonter les obstacles majeurs et de réaliser des initiatives stratégiques clés.", action: "Décomposez les projets complexes en tâches gérables, identifiez les interdépendances, gérez les ressources et les risques associés.", kpi: "GÈRE LES DÉFIS MAJEURS\nTROUVE DES SOLUTIONS INNOVANTES\nATTEINT LES OBJECTIFS AMBITIEUX" },
  ],

  // PAGE 7: PROFITABILITY
  profitability: [
    { title: "Flux de Trésorerie", definition: "Mouvement des liquidités entrant et sortant de l'entreprise.", subtitle: "Une gestion efficace assure la solvabilité et le financement des opérations quotidiennes.", action: "Suivez de près les entrées et sorties de liquidités, élaborez des prévisions de trésorerie.", kpi: "SUIT LES ENTRÉES ET SORTIES\nANTICIPE LES BESOINS EN LIQUIDITÉS\nMAINTIENT UNE TRÉSORERIE SAINE" },
    { title: "Répartition des Coûts", definition: "Analyse de la distribution des dépenses de l'entreprise.", subtitle: "Identifie où les coûts peuvent être réduits ou optimisés pour améliorer la rentabilité.", action: "Identifiez où sont dépensés les fonds, classez les coûts en variables et fixes, directs et indirects.", kpi: "IDENTIFIE LES POSTES DE DÉPENSES\nCONTRÔLE LES COÛTS\nOPTIMISE LE BUDGET" },
    { title: "Augmentation des Revenus", definition: "Stratégies pour accroître les revenus générés par l'entreprise.", subtitle: "Essentiel pour la croissance, l'expansion et l'amélioration de la rentabilité globale.", action: "Explorez de nouvelles sources de revenus, augmentez les ventes, diversifiez les offres.", kpi: "DÉVELOPPE LES VENTES\nDIVERSIFIE LES SOURCES DE REVENUS\nEXPLOITE DE NOUVEAUX MARCHÉS" },
    { title: "Réduction des Dépenses", definition: "Actions pour diminuer les coûts sans affecter la qualité.", subtitle: "Améliore la marge bénéficiaire et la compétitivité.", action: "Négociez avec les fournisseurs, optimisez les processus, éliminez les dépenses non essentielles.", kpi: "ÉLIMINE LES GASPILLAGES\nNÉGOCIE LES COÛTS\nAMÉLIORE L'EFFICACITÉ FINANCIÈRE" },
    { title: "Marges Bénéficiaires", definition: "Pourcentage de profit réalisé par rapport aux ventes.", subtitle: "Indicateur clé de la performance financière, influençant les décisions stratégiques.", action: "Calculez régulièrement les marges brutes et nettes, analysez leur évolution.", kpi: "CALCULE LES MARGES\nAUGMENTE LA RENTABILITÉ\nAMÉLIORE LA PERFORMANCE FINANCIÈRE" },
    { title: "Retour sur Investissement (ROI)", definition: "Mesure du gain ou de la perte générée par rapport au coût de l'investissement initial.", subtitle: "Aide à évaluer l'efficacité des investissements et à orienter les ressources.", action: "Analysez les gains ou pertes générés par rapport aux investissements réalisés, priorisez les projets avec le meilleur ROI.", kpi: "ÉVALUE LES INVESTISSEMENTS\nMESURE LES RENDEMENTS\nPREND DES DÉCISIONS ÉCLAIRÉES" },
    { title: "Gestion des Risques Financiers", definition: "Gestion des incertitudes liées aux finances de l'entreprise.", subtitle: "Protège contre les pertes financières imprévues et assure la stabilité à long terme.", action: "Identifiez les risques financiers (taux d'intérêt, change, crédit), utilisez des instruments de couverture si nécessaire.", kpi: "IDENTIFIE LES RISQUES\nMET EN PLACE DES COUVERTURES\nSÉCURISE LES ACTIFS" },
    { title: "Indicateurs Financiers", definition: "Données chiffrées pour évaluer la santé financière.", subtitle: "Fournissent des informations pour prendre des décisions éclairées et ajuster la stratégie financière.", action: "Mettez en place des tableaux de bord avec des KPI tels que le chiffre d'affaires, les marges, le résultat net, le point mort.", kpi: "SUIT LES KPIS CLÉS\nANALYSE LES TENDANCES\nINFORME LES DÉCISIONS STRATÉGIQUES" },
    { title: "Stratégie de Prix", definition: "Méthodes pour fixer les prix afin d'atteindre les objectifs.", subtitle: "Influence directement les ventes, la rentabilité et la perception de la valeur par les clients.", action: "Évaluez le positionnement prix, testez différentes approches (prix premium, pénétration, alignement sur la concurrence).", kpi: "ADAPTE LES PRIX AU MARCHÉ\nOPTIMISE LE POSITIONNEMENT\nMAXIMISE LES PROFITS" },
    { title: "Capitalisation", definition: "Valeur totale des actions de l'entreprise sur le marché.", subtitle: "Affecte la capacité à lever des fonds, à investir dans de nouveaux projets et à attirer des investisseurs.", action: "Déterminez les besoins en fonds propres, explorez les options de financement (investisseurs, levée de fonds, introduction en bourse).", kpi: "ACCROÎT LA VALEUR DE L'ENTREPRISE\nPRÉPARE LES LEVÉES DE FONDS\nATTIRE LES INVESTISSEURS" },
    { title: "Assurance", definition: "Protection financière contre les pertes imprévues.", subtitle: "Protège les actifs et assure la continuité des opérations en cas d'événements inattendus.", action: "Souscrivez des assurances appropriées (responsabilité civile, pertes d'exploitation, cyber-risques).", kpi: "PROTÈGE LES ACTIFS\nPRÉVOIT LES IMPRÉVUS\nRÉDUIT LES IMPACTS FINANCIERS" },
    { title: "Gestion des Crédits", definition: "Administration des dettes et emprunts pour maintenir la solvabilité.", subtitle: "Gérer efficacement les crédits évite les défauts de paiement et optimise les coûts financiers.", action: "Mettez en place des politiques de crédit, suivez les délais de paiement, négociez des conditions avantageuses.", kpi: "GÈRE LES DETTES\nNÉGOCIE LES TAUX\nASSURE LA SOLVABILITÉ" },
    { title: "Rotation des Stocks", definition: "Fréquence à laquelle l'inventaire est vendu et remplacé.", subtitle: "Une rotation efficace réduit les coûts de stockage et évite l'obsolescence, améliorant la rentabilité.", action: "Évitez les surstocks ou les ruptures, utilisez des techniques comme le Juste-à-Temps, analysez la rotation des stocks.", kpi: "OPTIMISE LES NIVEAUX DE STOCK\nRÉDUIT LES COÛTS DE STOCKAGE\nAMÉLIORE LE CASH-FLOW" },
    { title: "Compliance Financière", definition: "Respect des réglementations et normes financières.", subtitle: "Évite les sanctions légales, renforce la confiance des investisseurs et maintient la réputation.", action: "Respectez les obligations légales en matière de comptabilité, de fiscalité, faites réaliser des audits si nécessaire.", kpi: "RESPECTE LES NORMES COMPTABLES\nPASSE LES AUDITS\nÉVITE LES SANCTIONS" },
    { title: "Épargne", definition: "Mise de côté de fonds pour des besoins futurs ou imprévus.", subtitle: "Offre une sécurité financière en cas de fluctuations du marché ou de dépenses imprévues.", action: "Mettez de côté une partie des bénéfices pour faire face aux imprévus ou financer des projets futurs.", kpi: "CONSTITUE DES RÉSERVES\nPRÉVOIT POUR LE FUTUR\nGÈRE LES EXCÉDENTS" },
    { title: "Investissement Durable", definition: "Investissement dans des projets générant des rendements à long terme tout en étant responsables.", subtitle: "Aligne les objectifs financiers avec le développement durable.", action: "Choisissez des investissements qui allient rentabilité économique et impact social ou environnemental positif.", kpi: "INVESTIT DANS DES PROJETS À LONG TERME\nSOUTIENT LE DÉVELOPPEMENT DURABLE\nGÉNÈRE DES RENDEMENTS STABLES" },
    { title: "Diversification", definition: "Répartition des investissements pour réduire les risques.", subtitle: "Réduit l'impact des fluctuations dans un secteur, stabilisant les revenus.", action: "Développez de nouveaux produits, explorez de nouveaux marchés, investissez dans différents secteurs.", kpi: "ÉLARGIT LES SOURCES DE REVENUS\nINVESTIT DANS DIFFÉRENTS SECTEURS\nRÉDUIT LES RISQUES GLOBAUX" },
    { title: "Gestion des Devises", definition: "Administration des transactions en devises étrangères.", subtitle: "Essentielle pour les opérations internationales, influençant les coûts et les marges.", action: "Si vous opérez à l'international, surveillez les fluctuations des devises, utilisez des contrats à terme si nécessaire.", kpi: "GÈRE LES OPÉRATIONS INTERNATIONALES\nPROTÈGE CONTRE LES FLUCTUATIONS\nOPTIMISE LES TRANSACTIONS" },
    { title: "Optimisation Fiscale", definition: "Utilisation légale des dispositions pour réduire la charge fiscale.", subtitle: "Libère des ressources financières pour réinvestir ou augmenter les bénéfices nets.", action: "Utilisez les dispositifs légaux pour réduire les impôts (crédits d'impôt, amortissements, filiales à l'étranger).", kpi: "TIRE PARTI DES AVANTAGES FISCAUX\nPLANIFIE LES IMPÔTS\nRESPECTE LES LOIS FISCALES" },
    { title: "Atteinte des Objectifs Financiers", definition: "Réalisation des buts financiers fixés.", subtitle: "Indique le succès de la stratégie financière et la santé globale de l'entreprise.", action: "Fixez des objectifs financiers clairs (CA, bénéfices, ratios financiers), suivez les progrès, ajustez les stratégies si nécessaire.", kpi: "RÉALISE LES PRÉVISIONS\nSURPASSE LES ATTENTES\nCÉLÈBRE LES RÉUSSITES FINANCIÈRES" },
  ],

  // PAGE 8: INDICATORS
  indicators: [
    { title: "Chiffre d'Affaires", definition: "Total des ventes réalisées sur une période donnée.", subtitle: "Indicateur clé de la performance financière, reflétant la capacité à générer des revenus.", action: "Mesurez régulièrement le total des ventes réalisées sur une période donnée.", kpi: "CROISSANCE RÉGULIÈRE DES VENTES\nATTEINTE DES OBJECTIFS DE VENTE\nCOMPARAISON POSITIVE AVEC LE SECTEUR" },
    { title: "Croissance du Chiffre d'Affaires", definition: "Pourcentage d'augmentation des ventes par rapport à une période précédente.", subtitle: "Montre la dynamique de l'entreprise et son potentiel d'expansion sur le marché.", action: "Calculez le pourcentage d'augmentation des ventes par rapport à une période précédente.", kpi: "TAUX DE CROISSANCE ANNUEL ÉLEVÉ\nSURPASSE LES CONCURRENTS\nRESPECT DES PRÉVISIONS DE CROISSANCE" },
    { title: "Marge Bénéficiaire", definition: "Différence entre les revenus et les coûts, exprimée en pourcentage.", subtitle: "Indique la rentabilité des produits ou services, essentielle pour la viabilité à long terme.", action: "Déterminez la différence entre les revenus et les coûts, exprimée en pourcentage.", kpi: "MARGES SUPÉRIEURES À LA MOYENNE DU SECTEUR\nAMÉLIORATION CONTINUE DES MARGES\nCONTRÔLE DES COÛTS" },
    { title: "Part de Marché", definition: "Pourcentage des ventes de l'entreprise par rapport au total du marché.", subtitle: "Mesure la compétitivité et l'influence de l'entreprise dans son secteur.", action: "Calculez le pourcentage des ventes de votre entreprise par rapport au total du marché.", kpi: "AUGMENTATION DE LA PART DE MARCHÉ\nPOSITIONNEMENT PARMI LES LEADERS\nCONQUÊTE DE NOUVEAUX SEGMENTS" },
    { title: "Satisfaction Client", definition: "Niveau de satisfaction exprimé par les clients via des enquêtes ou feedbacks.", subtitle: "Influence la fidélité, les recommandations et la réputation de l'entreprise.", action: "Recueillez les feedbacks clients via des enquêtes, des avis ou des scores NPS (Net Promoter Score).", kpi: "SCORES ÉLEVÉS DANS LES ENQUÊTES\nRÉDUCTION DES PLAINTES\nTAUX DE RECOMMANDATION POSITIF (NPS)" },
    { title: "Taux de Rétention Client", definition: "Nombre de clients récurrents par rapport au total de clients.", subtitle: "La fidélisation réduit les coûts d'acquisition et augmente la valeur à long terme des clients.", action: "Calculez le pourcentage de clients qui continuent à acheter vos produits ou services sur une période donnée.", kpi: "TAUX DE RÉTENTION ÉLEVÉ\nAUGMENTATION DES ACHATS RÉPÉTÉS\nDIMINUTION DU TAUX D'ATTRITION" },
    { title: "Nombre de Nouveaux Clients", definition: "Compte des clients qui effectuent un premier achat.", subtitle: "Indicateur de la croissance du marché et de l'efficacité des stratégies d'acquisition.", action: "Suivez le nombre de nouveaux clients acquis et analysez les canaux d'acquisition les plus efficaces.", kpi: "AUGMENTATION DU NOMBRE DE NOUVEAUX CLIENTS\nEFFICACITÉ DES CAMPAGNES MARKETING\nEXPANSION DANS DE NOUVEAUX MARCHÉS" },
    { title: "Retour sur Investissement (ROI)", definition: "Ratio mesurant la performance financière des investissements.", subtitle: "Aide à évaluer l'efficacité des dépenses et à orienter les ressources vers les projets les plus rentables.", action: "Mesurez le gain ou la perte généré par rapport au coût des investissements spécifiques (campagnes, projets).", kpi: "ROI POSITIF ET CROISSANT\nINVESTISSEMENTS RENTABLES\nDÉCISIONS D'INVESTISSEMENT ÉCLAIRÉES" },
    { title: "Valeur à Vie du Client (CLV)", definition: "Total des profits générés par un client tout au long de sa relation avec l'entreprise.", subtitle: "Encourage des stratégies axées sur la fidélisation et l'augmentation de la valeur des clients existants.", action: "Estimez le total des profits qu'un client génère tout au long de sa relation avec votre entreprise.", kpi: "CLV ÉLEVÉE\nAUGMENTATION DES ACHATS PAR CLIENT\nPROGRAMMES DE FIDÉLISATION EFFICACES" },
    { title: "Coût d'Acquisition Client (CAC)", definition: "Total des dépenses marketing et commerciales divisé par le nombre de nouveaux clients acquis.", subtitle: "Optimiser le CAC permet d'améliorer la rentabilité et l'efficacité des efforts d'acquisition.", action: "Calculez le coût moyen pour acquérir un nouveau client en divisant les dépenses marketing par le nombre de clients acquis.", kpi: "CAC RÉDUIT\nAMÉLIORATION DU RATIO CLV/CAC\nOPTIMISATION DES DÉPENSES MARKETING" },
    { title: "Taux de Conversion", definition: "Nombre de conversions divisé par le nombre total de prospects, exprimé en pourcentage.", subtitle: "Indicateur de l'efficacité du processus de vente et des campagnes marketing.", action: "Mesurez le pourcentage de prospects convertis en clients payants.", kpi: "TAUX DE CONVERSION ÉLEVÉ\nAMÉLIORATION CONTINUE\nOPTIMISATION DU PARCOURS CLIENT" },
    { title: "Notoriété de la Marque", definition: "Mesure de la visibilité et de la reconnaissance de la marque sur le marché.", subtitle: "Une forte notoriété facilite l'acquisition de clients et renforce la position concurrentielle.", action: "Évaluez la reconnaissance de votre marque via des études de marché, le suivi des mentions et la présence médiatique.", kpi: "AUGMENTATION DES MENTIONS DE LA MARQUE\nPRÉSENCE MÉDIATIQUE ACCRUE\nRECONNAISSANCE SPONTANÉE ÉLEVÉE" },
    { title: "Engagement des Employés", definition: "Mesuré par des enquêtes internes et le taux de participation aux initiatives.", subtitle: "Un personnel engagé est plus productif, innovant et contribue à la réussite globale de l'entreprise.", action: "Réalisez des enquêtes internes pour évaluer la motivation et l'implication des employés.", kpi: "SCORES ÉLEVÉS D'ENGAGEMENT\nFAIBLE TAUX DE ROTATION DU PERSONNEL\nPARTICIPATION ACTIVE AUX PROJETS" },
    { title: "Productivité", definition: "Ratio de production par unité de ressource (temps, coût, personnel).", subtitle: "Améliorer la productivité augmente la rentabilité et la compétitivité.", action: "Suivez les indicateurs de performance tels que la production par employé ou le temps nécessaire pour accomplir des tâches.", kpi: "AUGMENTATION DE LA PRODUCTION PAR EMPLOYÉ\nRÉDUCTION DES COÛTS OPÉRATIONNELS\nOPTIMISATION DES PROCESSUS" },
    { title: "Innovation", definition: "Nombre de nouvelles idées mises en œuvre ou brevets déposés.", subtitle: "L'innovation permet de se différencier et de répondre aux évolutions du marché.", action: "Mesurez le nombre de nouveaux produits, services ou améliorations développés sur une période donnée.", kpi: "LANCEMENT RÉGULIER DE NOUVEAUTÉS\nINVESTISSEMENT EN R&D\nADOPTION DES INNOVATIONS PAR LE MARCHÉ" },
    { title: "Durabilité Environnementale", definition: "Mesure des émissions, consommation d'énergie, gestion des déchets, etc.", subtitle: "Répond aux attentes croissantes des clients et régulateurs, et peut réduire les coûts à long terme.", action: "Suivez les indicateurs tels que la réduction des émissions, la consommation d'énergie ou la gestion des déchets.", kpi: "RÉDUCTION DES ÉMISSIONS DE CO2\nCERTIFICATIONS ENVIRONNEMENTALES OBTENUES\nMISE EN PLACE DE PRATIQUES DURABLES" },
    { title: "Diversification des Produits", definition: "Nombre de nouveaux produits lancés dans différents segments.", subtitle: "Réduit les risques liés à un seul produit et peut ouvrir de nouveaux marchés.", action: "Évaluez le pourcentage de revenus provenant de nouveaux produits ou services.", kpi: "AUGMENTATION DU PORTEFEUILLE PRODUITS\nPART DES REVENUS PROVENANT DE NOUVEAUX PRODUITS\nRÉUSSITE DES LANCEMENTS" },
    { title: "Expansion Géographique", definition: "Nombre de nouveaux pays ou régions où l'entreprise est présente.", subtitle: "Permet de toucher une clientèle plus large et diversifie les sources de revenus.", action: "Suivez le nombre de nouveaux marchés ou régions où vous êtes présent.", kpi: "OUVERTURE DE NOUVEAUX MARCHÉS\nCROISSANCE DES VENTES À L'INTERNATIONAL\nADAPTATION RÉUSSIE AUX MARCHÉS LOCAUX" },
    { title: "Indice de Satisfaction des Employés", definition: "Résultats d'enquêtes internes sur la satisfaction au travail.", subtitle: "Des employés satisfaits sont plus productifs et contribuent à une meilleure ambiance de travail.", action: "Mesurez le niveau de satisfaction des employés via des enquêtes et le suivi du taux d'absentéisme.", kpi: "SCORES ÉLEVÉS DE SATISFACTION\nFAIBLE TAUX D'ABSENTÉISME\nCULTURE D'ENTREPRISE POSITIVE" },
    { title: "Impact Social", definition: "Actions en faveur de la communauté, philanthropie, initiatives sociales.", subtitle: "Renforce la réputation, la loyauté des clients et répond aux attentes des parties prenantes.", action: "Évaluez les contributions à la communauté, les initiatives philanthropiques ou les impacts sociaux positifs.", kpi: "PROGRAMMES SOCIAUX MIS EN PLACE\nINVESTISSEMENT COMMUNAUTAIRE\nRECONNAISSANCE PAR DES ORGANISMES EXTERNES" },
  ],

  // PAGE 9: MANAGING
  managing: [
    { title: "Leadership", definition: "Capacité à inspirer et guider une équipe vers un objectif commun.", subtitle: "Un bon leadership motive l'équipe, favorise l'innovation et assure l'alignement sur la vision de l'entreprise.", action: "Identifiez votre style de leadership, inspirez votre équipe et communiquez une vision claire.", kpi: "CLARTÉ DE LA VISION\nENGAGEMENT DE L'ÉQUIPE\nATTEINTE DES OBJECTIFS" },
    { title: "Communication", definition: "Processus d'échange d'informations de manière claire et efficace.", subtitle: "Essentielle pour éviter les malentendus, renforcer la cohésion d'équipe et assurer la réussite des projets.", action: "Mettez en place des canaux de communication efficaces, pratiquez l'écoute active et encouragez le feedback.", kpi: "FEEDBACK RÉGULIER\nRÉUNIONS EFFICACES\nTRANSPARENCE DE L'INFORMATION" },
    { title: "Délégation", definition: "Action de confier des responsabilités à d'autres membres de l'équipe.", subtitle: "Permet d'optimiser le temps du manager et de développer les compétences de l'équipe.", action: "Identifiez les tâches à déléguer, choisissez les bonnes personnes et définissez clairement les attentes.", kpi: "RÉPARTITION ÉQUILIBRÉE DES TÂCHES\nAUTONOMIE DES EMPLOYÉS\nEFFICACITÉ OPÉRATIONNELLE" },
    { title: "Motivation", definition: "Processus visant à encourager et stimuler l'engagement des employés.", subtitle: "Augmente la productivité, la satisfaction au travail et réduit le turnover du personnel.", action: "Reconnaissez les accomplissements, offrez des opportunités de développement et créez un environnement positif.", kpi: "TAUX D'ENGAGEMENT ÉLEVÉ\nRÉDUCTION DE L'ABSENTÉISME\nATTEINTE DES OBJECTIFS INDIVIDUELS" },
    { title: "Team Building", definition: "Activités pour renforcer la cohésion et la collaboration au sein de l'équipe.", subtitle: "Améliore la communication, la confiance et l'efficacité collective.", action: "Organisez des activités de team building, encouragez la collaboration et valorisez les contributions de chacun.", kpi: "ESPRIT D'ÉQUIPE FORT\nCOLLABORATION ACCRUE\nRÉSOLUTION EFFICACE DES CONFLITS" },
    { title: "Résolution de Conflits", definition: "Processus de gestion et de résolution des désaccords entre individus.", subtitle: "Maintient un environnement de travail sain et productif, évitant les perturbations.", action: "Identifiez rapidement les sources de conflits, facilitez la discussion et trouvez des solutions mutuellement acceptables.", kpi: "DIMINUTION DES CONFLITS\nRAPIDITÉ DE RÉSOLUTION\nSATISFACTION DES PARTIES IMPLIQUÉES" },
    { title: "Prise de Décision", definition: "Sélection d'une option parmi plusieurs pour résoudre un problème ou saisir une opportunité.", subtitle: "Cruciale pour avancer rapidement et orienter l'entreprise vers ses objectifs.", action: "Collectez les informations nécessaires, évaluez les options et assumez vos décisions.", kpi: "DÉCISIONS RAPIDES ET ÉCLAIRÉES\nIMPLICATION DE L'ÉQUIPE\nSUCCÈS DES DÉCISIONS PRISES" },
    { title: "Gestion du Temps", definition: "Capacité à planifier et organiser son temps et celui de l'équipe efficacement.", subtitle: "Essentielle pour respecter les délais et augmenter la productivité.", action: "Priorisez les tâches, évitez la procrastination et utilisez des outils de planification.", kpi: "RESPECT DES ÉCHÉANCES\nPRIORISATION EFFICACE\nRÉDUCTION DU STRESS LIÉ AU TEMPS" },
    { title: "Planification Stratégique", definition: "Processus de définition des stratégies pour atteindre les objectifs à long terme.", subtitle: "Guide les actions quotidiennes et assure l'alignement sur la vision de l'entreprise.", action: "Définissez des objectifs à long terme, analysez l'environnement interne et externe, établissez des plans d'action.", kpi: "OBJECTIFS CLAIRS ET ALIGNÉS\nSUIVI DES INDICATEURS CLÉS\nADAPTABILITÉ DE LA STRATÉGIE" },
    { title: "Gestion du Changement", definition: "Approche pour gérer les transitions organisationnelles ou structurelles.", subtitle: "Permet d'accompagner l'équipe à travers les changements et de minimiser la résistance.", action: "Communiquez clairement sur les changements, impliquez l'équipe et gérez les résistances.", kpi: "ADOPTION RAPIDE DES CHANGEMENTS\nCOMMUNICATION EFFICACE SUR LES CHANGEMENTS\nMAINTIEN DE LA PRODUCTIVITÉ" },
    { title: "Intelligence Émotionnelle", definition: "Capacité à reconnaître, comprendre et gérer ses émotions et celles des autres.", subtitle: "Améliore les relations interpersonnelles et la gestion des équipes.", action: "Prenez conscience de vos émotions, gérez-les efficacement et comprenez celles des autres.", kpi: "EMPATHIE DÉMONTRÉE\nGESTION DU STRESS\nRELATIONS POSITIVES AU TRAVAIL" },
    { title: "Gestion de la Performance", definition: "Processus pour évaluer et améliorer les performances individuelles et collectives.", subtitle: "Assure que les objectifs sont atteints et que l'équipe progresse.", action: "Fixez des objectifs clairs, fournissez un feedback régulier et soutenez le développement de l'équipe.", kpi: "OBJECTIFS INDIVIDUELS DÉFINIS\nFEEDBACK RÉGULIER\nAMÉLIORATION DES PERFORMANCES" },
    { title: "Feedback Constructif", definition: "Retour d'information visant à améliorer les compétences ou les performances.", subtitle: "Favorise le développement professionnel et l'amélioration continue.", action: "Apprenez à formuler des feedbacks constructifs, soyez ouvert aux retours et utilisez-les pour vous améliorer.", kpi: "FEEDBACK RÉGULIER ET ÉQUILIBRÉ\nRÉCEPTIVITÉ DE L'ÉQUIPE\nMISE EN ŒUVRE DES AMÉLIORATIONS" },
    { title: "Coaching et Mentorat", definition: "Accompagnement individuel pour développer les compétences et le potentiel.", subtitle: "Aide les employés à progresser et à atteindre leurs objectifs de carrière.", action: "Identifiez les besoins en développement, offrez du coaching et créez des opportunités de mentorat.", kpi: "PROGRAMMES DE MENTORAT EN PLACE\nPROGRESSION DES EMPLOYÉS\nSATISFACTION AU TRAVAIL ACCRUE" },
    { title: "Culture d'Entreprise", definition: "Ensemble des valeurs, croyances et comportements partagés au sein de l'organisation.", subtitle: "Influence la motivation, l'engagement et l'identité de l'entreprise.", action: "Définissez et communiquez les valeurs de l'entreprise, encouragez les comportements alignés et célébrez les réussites.", kpi: "VALEURS CLAIREMENT DÉFINIES\nCOHÉRENCE DES COMPORTEMENTS\nATTRACTION DES TALENTS" },
    { title: "Gestion des Risques", definition: "Identification et gestion des risques potentiels affectant l'entreprise.", subtitle: "Réduit l'impact des incertitudes sur les objectifs de l'entreprise.", action: "Évaluez les risques potentiels, élaborez des plans de mitigation et surveillez régulièrement les risques.", kpi: "PLAN DE GESTION DES RISQUES\nRÉDUCTION DES INCIDENTS\nPRÉPARATION AUX IMPRÉVUS" },
    { title: "Négociation", definition: "Processus de discussion visant à parvenir à un accord mutuellement bénéfique.", subtitle: "Essentielle pour conclure des accords avec les clients, fournisseurs et partenaires.", action: "Préparez-vous soigneusement, comprenez les besoins de l'autre partie et cherchez des solutions gagnant-gagnant.", kpi: "ACCORDS CONCLUS AVEC SUCCÈS\nRELATIONS DURABLES\nCONDITIONS AVANTAGEUSES OBTENUES" },
    { title: "Diversité et Inclusion", definition: "Promotion d'un environnement où toutes les différences sont respectées et valorisées.", subtitle: "Stimule l'innovation, la créativité et améliore la performance globale.", action: "Mettez en place des politiques inclusives, formez l'équipe à la diversité et valorisez les différences.", kpi: "REPRÉSENTATION DIVERSE\nSENTIMENT D'INCLUSION\nINNOVATION ACCRUE" },
    { title: "Gestion des Parties Prenantes", definition: "Identification et engagement avec les personnes influençant ou étant influencées par l'entreprise.", subtitle: "Assure une communication efficace et renforce les relations clés pour le succès du projet.", action: "Identifiez les parties prenantes clés, comprenez leurs attentes et communiquez régulièrement avec elles.", kpi: "CARTOGRAPHIE DES PARTIES PRENANTES\nENGAGEMENT ACTIF\nSATISFACTION DES PARTIES PRENANTES" },
    { title: "Amélioration Continue", definition: "Philosophie de travail visant à améliorer constamment les processus et les pratiques.", subtitle: "Permet à l'entreprise de rester compétitive et d'augmenter l'efficacité.", action: "Encouragez l'équipe à proposer des améliorations, mettez en place des processus d'évaluation et célébrez les progrès.", kpi: "PROCESSUS D'ÉVALUATION RÉGULIERS\nMISE EN PLACE D'INNOVATIONS\nGAINS D'EFFICACITÉ RÉALISÉS" },
  ],

  // PAGE 10: FINANCE
  finance: [
    { title: "Analyse Financière", definition: "Étude détaillée des états financiers pour comprendre la performance.", subtitle: "Permet de prendre des décisions éclairées basées sur des données financières solides.", action: "Examinez vos états financiers pour comprendre la performance de votre entreprise.", kpi: "ÉTATS FINANCIERS À JOUR\nANALYSE RÉGULIÈRE DES INDICATEURS\nDÉCISIONS BASÉES SUR L'ANALYSE" },
    { title: "Gestion de la Trésorerie", definition: "Gestion des entrées et sorties de liquidités de l'entreprise.", subtitle: "Essentielle pour assurer la solvabilité et éviter les pénuries de liquidités.", action: "Surveillez les flux de trésorerie, prévoyez les besoins en liquidités et gérez les entrées et sorties.", kpi: "PRÉVISIONS DE TRÉSORERIE\nSOLDE POSITIF CONSTANT\nOPTIMISATION DU CASH-FLOW" },
    { title: "Contrôle des Coûts", definition: "Surveillance et réduction des dépenses pour augmenter la rentabilité.", subtitle: "Aide à maximiser les profits en évitant les dépenses inutiles.", action: "Identifiez les dépenses superflues, négociez avec les fournisseurs et optimisez les processus pour réduire les coûts.", kpi: "BUDGET RESPECTÉ\nRÉDUCTION DES COÛTS SUPERFLUS\nMARGES BÉNÉFICIAIRES AMÉLIORÉES" },
    { title: "Marge Brute", definition: "Différence entre le chiffre d'affaires et le coût des ventes.", subtitle: "Indicateur clé de la rentabilité opérationnelle de l'entreprise.", action: "Analysez la marge brute par produit ou service et identifiez les moyens de l'améliorer.", kpi: "MARGES BRUTES ÉLEVÉES\nAMÉLIORATION CONTINUE\nCOMPARAISON FAVORABLE AVEC LE SECTEUR" },
    { title: "Bilan", definition: "Document financier présentant les actifs, passifs et capitaux propres.", subtitle: "Offre une image de la santé financière à un moment donné.", action: "Préparez un bilan pour évaluer la santé financière de votre entreprise à des intervalles réguliers.", kpi: "BILAN ÉQUILIBRÉ\nRATIO D'ENDETTEMENT SAIN\nACTIFS EN CROISSANCE" },
    { title: "Cycle d'Exploitation", definition: "Durée entre l'achat de matières premières et la réception du paiement client.", subtitle: "Affecte la liquidité et les besoins en fonds de roulement.", action: "Optimisez les processus d'achat, de production et de vente pour accélérer le cycle.", kpi: "CYCLE RÉDUIT\nROTATION DES STOCKS EFFICACE\nDÉLAI DE PAIEMENT OPTIMISÉ" },
    { title: "Gestion de la Dette", definition: "Stratégie pour gérer les emprunts et les obligations financières.", subtitle: "Évite le surendettement et optimise les coûts financiers.", action: "Établissez un plan pour rembourser les dettes, négociez les conditions et évitez le surendettement.", kpi: "RATIO D'ENDETTEMENT MAÎTRISÉ\nRESPECT DES ÉCHÉANCES\nCOÛT DE LA DETTE OPTIMISÉ" },
    { title: "Prix de Revient", definition: "Coût total pour produire un produit ou service.", subtitle: "Aide à fixer des prix compétitifs tout en assurant la rentabilité.", action: "Additionnez tous les coûts directs et indirects pour chaque produit ou service.", kpi: "CONNAISSANCE PRÉCISE DES COÛTS\nMARGES BÉNÉFICIAIRES ADÉQUATES\nAJUSTEMENT DES PRIX SI NÉCESSAIRE" },
    { title: "Culture Financière", definition: "Niveau de compréhension des concepts financiers par le dirigeant.", subtitle: "Permet de prendre des décisions stratégiques éclairées et de communiquer efficacement avec les investisseurs.", action: "Formez-vous aux concepts financiers, participez à des ateliers et encouragez votre équipe à faire de même.", kpi: "FORMATION FINANCIÈRE SUIVIE\nCOMPRÉHENSION DES RAPPORTS FINANCIERS\nIMPLICATION DANS LES DÉCISIONS FINANCIÈRES" },
    { title: "Budget Prévisionnel", definition: "Plan financier détaillant les prévisions de revenus et de dépenses.", subtitle: "Sert de guide pour les opérations et permet de contrôler les performances réelles.", action: "Définissez des prévisions de revenus et de dépenses pour planifier les opérations futures.", kpi: "ÉLABORATION DU BUDGET\nSUIVI RÉGULIER\nÉCARTS ANALYSÉS ET CORRIGÉS" },
    { title: "Reporting Financier", definition: "Communication régulière des performances financières aux parties prenantes.", subtitle: "Renforce la transparence et la confiance des investisseurs et partenaires.", action: "Créez des rapports financiers périodiques pour les investisseurs, partenaires et l'équipe interne.", kpi: "RAPPORTS PÉRIODIQUES PRODUITS\nINDICATEURS CLÉS SUIVIS\nCOMMUNICATION CLAIRE" },
    { title: "Levée de Fonds", definition: "Processus de collecte de capitaux auprès d'investisseurs ou de prêteurs.", subtitle: "Nécessaire pour financer la croissance et les investissements majeurs.", action: "Identifiez les besoins en financement, préparez un pitch convaincant et contactez des investisseurs potentiels.", kpi: "OBJECTIFS DE FINANCEMENT CLAIRS\nPRÉSENTATIONS EFFICACES AUX INVESTISSEURS\nFONDS LEVÉS AVEC SUCCÈS" },
    { title: "Retour sur Investissement", definition: "Mesure de la rentabilité des investissements réalisés.", subtitle: "Aide à évaluer l'efficacité des dépenses en capital et à orienter les futurs investissements.", action: "Mesurez la rentabilité des investissements en comparant les gains réalisés aux coûts engagés.", kpi: "ROI CALCULÉ POUR CHAQUE PROJET\nINVESTISSEMENTS RENTABLES\nDÉCISIONS BASÉES SUR LE ROI" },
    { title: "Gestion des Risques Financiers", definition: "Identification et mitigation des risques financiers.", subtitle: "Protège l'entreprise contre les fluctuations du marché et les imprévus financiers.", action: "Analysez les risques potentiels (taux d'intérêt, change, crédit) et élaborez des stratégies pour les atténuer.", kpi: "PLANS DE CONTINGENCE EN PLACE\nASSURANCE ADÉQUATE\nDIVERSIFICATION DES REVENUS" },
    { title: "Objectifs Financiers", definition: "Définition claire des buts financiers à atteindre.", subtitle: "Oriente les efforts et permet de mesurer le succès financier de l'entreprise.", action: "Établissez des objectifs SMART pour les revenus, les marges, les coûts et autres indicateurs financiers.", kpi: "OBJECTIFS SMART DÉFINIS\nSUIVI RÉGULIER\nATTEINTE DES OBJECTIFS" },
    { title: "Compliance Financière", definition: "Respect des lois et réglementations financières en vigueur.", subtitle: "Évite les sanctions légales et protège la réputation de l'entreprise.", action: "Mettez en place des processus pour respecter les réglementations financières et fiscales.", kpi: "CONFORMITÉ LÉGALE ASSURÉE\nAUDITS RÉUSSIS\nPAS DE SANCTIONS OU PÉNALITÉS" },
    { title: "Point Mort (Seuil de Rentabilité)", definition: "Niveau de ventes nécessaire pour couvrir tous les coûts.", subtitle: "Aide à fixer des objectifs de vente et à comprendre la structure des coûts.", action: "Déterminez le volume de ventes nécessaire pour couvrir tous les coûts fixes et variables.", kpi: "POINT MORT CALCULÉ\nATTEINTE DU SEUIL DE RENTABILITÉ\nOPTIMISATION POUR LE RÉDUIRE" },
    { title: "Prévisions Financières", definition: "Estimations des performances financières futures.", subtitle: "Permet de planifier les ressources et de préparer les stratégies d'expansion ou de réduction.", action: "Utilisez des modèles pour estimer les performances futures basées sur les données historiques et les tendances.", kpi: "MODÈLES DE PRÉVISION ÉTABLIS\nPRÉCISION DES PRÉVISIONS\nAJUSTEMENTS BASÉS SUR LES ÉCARTS" },
    { title: "Investissements à Long Terme", definition: "Allocation de ressources pour des bénéfices futurs sur le long terme.", subtitle: "Soutient la croissance durable et la compétitivité future.", action: "Identifiez les projets stratégiques qui soutiendront la croissance future et allouez les ressources nécessaires.", kpi: "INVESTISSEMENTS STRATÉGIQUES RÉALISÉS\nSUIVI DES PERFORMANCES À LONG TERME\nALIGNEMENT AVEC LA VISION" },
    { title: "Équilibre Financier", definition: "Situation où les ressources financières sont suffisantes pour couvrir les obligations.", subtitle: "Assure la stabilité financière et la pérennité de l'entreprise.", action: "Surveillez les ratios financiers clés et ajustez les stratégies pour maintenir une situation financière saine.", kpi: "RATIOS FINANCIERS SAINS\nTRÉSORERIE POSITIVE\nCAPACITÉ À FAIRE FACE AUX IMPRÉVUS" },
  ],

  // PAGE 11: GOUVERNANCE
  gouvernance: [
    { title: "Structure Organisationnelle", definition: "Disposition hiérarchique des rôles et responsabilités au sein de l'entreprise.", subtitle: "Clarifie les rôles, facilite la communication et assure une répartition efficace des tâches.", action: "Établissez un organigramme clair, définissez les rôles et responsabilités de chaque poste.", kpi: "ORGANIGRAMME DÉFINI\nRÔLES ET RESPONSABILITÉS CLAIRS\nCOMMUNICATION EFFICACE" },
    { title: "Conseil d'Administration", definition: "Groupe de personnes chargé de superviser et guider la direction stratégique.", subtitle: "Offre une supervision, des conseils et une expertise pour orienter l'entreprise vers le succès.", action: "Sélectionnez des membres compétents et diversifiés pour superviser la direction stratégique.", kpi: "CONSEIL ÉTABLI\nRÉUNIONS RÉGULIÈRES\nDIVERSITÉ DES COMPÉTENCES AU SEIN DU CONSEIL" },
    { title: "Conformité Réglementaire", definition: "Respect des lois, réglementations et normes applicables à l'entreprise.", subtitle: "Évite les sanctions légales, protège la réputation et assure la pérennité de l'entreprise.", action: "Identifiez les lois et réglementations applicables, mettez en place des processus pour y adhérer.", kpi: "CONFORMITÉ LÉGALE ASSURÉE\nAUDITS RÉUSSIS\nPAS DE SANCTIONS OU PÉNALITÉS" },
    { title: "Politiques et Procédures", definition: "Ensemble de directives formelles qui guident les opérations et les comportements.", subtitle: "Assure la cohérence, l'efficacité et le respect des normes au sein de l'entreprise.", action: "Documentez les directives pour les opérations et comportements, communiquez-les à l'équipe.", kpi: "POLITIQUES DOCUMENTÉES\nCOMMUNICATION À L'ÉQUIPE\nRESPECT DES PROCÉDURES" },
    { title: "Vision et Mission", definition: "Énoncé des objectifs fondamentaux et de la raison d'être de l'entreprise.", subtitle: "Guide la stratégie et les actions, aligne l'équipe sur des objectifs communs.", action: "Rédigez des énoncés clairs qui reflètent les objectifs fondamentaux de l'entreprise.", kpi: "VISION ET MISSION DÉFINIES\nCOMPRÉHENSION PAR L'ÉQUIPE\nALIGNEMENT DES ACTIONS" },
    { title: "Responsabilité Sociale", definition: "Engagement de l'entreprise envers la société et l'environnement.", subtitle: "Renforce la réputation, attire les clients et investisseurs soucieux de l'éthique.", action: "Identifiez les initiatives sociales et environnementales pertinentes, mettez-les en œuvre.", kpi: "INITIATIVES RSE EN PLACE\nIMPACT SOCIAL POSITIF\nCOMMUNICATION DES ACTIONS RSE" },
    { title: "Transparence", definition: "Communication ouverte et honnête des informations pertinentes aux parties prenantes.", subtitle: "Renforce la confiance, facilite la prise de décision et améliore les relations avec les parties prenantes.", action: "Communiquez ouvertement sur les performances, les décisions et les informations pertinentes.", kpi: "RAPPORTS TRANSPARENTS\nACCÈS À L'INFORMATION\nFEEDBACK POSITIF DES PARTIES PRENANTES" },
    { title: "Audit Interne", definition: "Évaluation indépendante des opérations pour assurer l'efficacité et la conformité.", subtitle: "Identifie les faiblesses, recommande des améliorations et assure la fiabilité des informations financières.", action: "Désignez une équipe ou un tiers pour évaluer les opérations et la conformité régulièrement.", kpi: "AUDITS RÉGULIERS\nRECOMMANDATIONS MISES EN ŒUVRE\nAMÉLIORATION DES PROCESSUS" },
    { title: "Éthique Professionnelle", definition: "Ensemble de principes moraux guidant le comportement au travail.", subtitle: "Maintient l'intégrité, évite les conflits d'intérêts et protège la réputation de l'entreprise.", action: "Définissez les principes moraux guidant le comportement au travail, formez l'équipe à ces standards.", kpi: "CODE D'ÉTHIQUE ÉTABLI\nFORMATION À L'ÉTHIQUE\nABSENCE DE VIOLATIONS ÉTHIQUES" },
    { title: "Relations avec les Parties Prenantes", definition: "Gestion des interactions avec les individus ou groupes affectés par les activités de l'entreprise.", subtitle: "Renforce les relations, anticipe les attentes et minimise les conflits.", action: "Identifiez les parties prenantes clés, communiquez régulièrement et répondez à leurs attentes.", kpi: "CARTOGRAPHIE DES PARTIES PRENANTES\nENGAGEMENT ACTIF\nSATISFACTION DES PARTIES PRENANTES" },
    { title: "Gestion des Politiques", definition: "Processus de création, mise à jour et communication des politiques internes.", subtitle: "Assure que les politiques restent pertinentes et alignées sur les objectifs de l'entreprise.", action: "Mettez en place un processus pour créer, mettre à jour et communiquer les politiques de l'entreprise.", kpi: "POLITIQUES À JOUR\nPROCESSUS DE RÉVISION EN PLACE\nCOMMUNICATION EFFICACE DES CHANGEMENTS" },
    { title: "Responsabilité Fiduciaire", definition: "Obligation de gérer les actifs de l'entreprise dans le meilleur intérêt des parties prenantes.", subtitle: "Protège les investissements, assure une gestion prudente des ressources financières.", action: "Gérez les actifs avec diligence, prenez des décisions financières dans le meilleur intérêt des parties prenantes.", kpi: "GESTION FINANCIÈRE RESPONSABLE\nCONFORMITÉ AUX OBLIGATIONS FIDUCIAIRES\nCONFIANCE DES INVESTISSEURS" },
    { title: "Succession et Continuité", definition: "Planification pour assurer la continuité des opérations en cas de départs clés.", subtitle: "Prépare l'entreprise aux imprévus, minimise les perturbations et assure la pérennité.", action: "Identifiez les postes clés, formez des remplaçants potentiels et établissez un plan de succession.", kpi: "PLAN DE SUCCESSION ÉTABLI\nFORMATION DES REMPLAÇANTS\nTRANSITION EN DOUCEUR LORS DES CHANGEMENTS" },
    { title: "Assemblées Générales", definition: "Réunions formelles des actionnaires ou membres pour discuter des affaires de l'entreprise.", subtitle: "Facilite la prise de décision collective et la communication des performances.", action: "Planifiez et conduisez des réunions avec les actionnaires pour discuter des affaires de l'entreprise.", kpi: "ASSEMBLÉES RÉGULIÈRES\nPARTICIPATION ACTIVE\nDÉCISIONS RATIFIÉES" },
    { title: "Protection des Données", definition: "Mesures pour sécuriser les informations sensibles et personnelles.", subtitle: "Évite les fuites d'informations, respecte les réglementations et maintient la confiance des clients.", action: "Adoptez des mesures de sécurité, formez l'équipe aux bonnes pratiques et respectez les réglementations.", kpi: "POLITIQUES DE SÉCURITÉ EN PLACE\nCONFORMITÉ RGPD (OU ÉQUIVALENT)\nABSENCE DE VIOLATIONS DE DONNÉES" },
    { title: "Performance du Conseil", definition: "Évaluation de l'efficacité et de la contribution du conseil d'administration.", subtitle: "Assure que le conseil apporte une réelle valeur ajoutée à l'entreprise.", action: "Réalisez des évaluations régulières, identifiez les domaines d'amélioration et mettez en place des formations.", kpi: "ÉVALUATIONS RÉGULIÈRES\nFORMATION CONTINUE DES MEMBRES\nAMÉLIORATION DES PRATIQUES DU CONSEIL" },
    { title: "Gestion des Conflits d'Intérêts", definition: "Identification et gestion des situations où les intérêts personnels peuvent influencer les décisions professionnelles.", subtitle: "Maintient l'intégrité et la confiance dans la prise de décision.", action: "Établissez des politiques claires, demandez des déclarations et prenez des mesures en cas de conflit.", kpi: "POLITIQUES CLAIRES\nDÉCLARATIONS DE CONFLITS\nACTIONS CORRECTIVES PRISES" },
    { title: "Respect des Délais Légaux", definition: "Adhérence aux échéances imposées par les lois et réglementations.", subtitle: "Évite les pénalités et démontre le professionnalisme de l'entreprise.", action: "Identifiez les échéances réglementaires, mettez en place des rappels et attribuez des responsabilités.", kpi: "RESPECT SYSTÉMATIQUE DES DÉLAIS\nAUCUN RETARD SIGNALÉ\nPROCESSUS DE SUIVI EN PLACE" },
    { title: "Équilibre Pouvoir/Contrôle", definition: "Répartition équilibrée du pouvoir décisionnel pour éviter les abus et favoriser la responsabilité.", subtitle: "Favorise une gouvernance saine et évite les dérives autoritaires.", action: "Mettez en place des mécanismes de contrôle, séparez les pouvoirs et encouragez la responsabilité.", kpi: "MÉCANISMES DE CONTRÔLE EN PLACE\nSÉPARATION DES POUVOIRS\nTRANSPARENCE DANS LA PRISE DE DÉCISION" },
    { title: "Objectifs Stratégiques", definition: "Définition des buts à long terme et des moyens pour les atteindre.", subtitle: "Aligne l'organisation sur une direction commune et mesure les progrès réalisés.", action: "Établissez des objectifs à long terme, élaborez des plans pour les atteindre et mesurez les progrès.", kpi: "OBJECTIFS CLAIRS ET COMMUNIQUÉS\nSUIVI RÉGULIER DES PROGRÈS\nATTEINTE DES OBJECTIFS FIXÉS" },
  ],

  // PAGE 12: FUNDRAISING
  fundraising: [
    { title: "Préparation du Pitch", definition: "Création d'une présentation convaincante pour les investisseurs.", subtitle: "Un pitch efficace capte l'attention des investisseurs et communique clairement la valeur de l'entreprise.", action: "Développez une présentation claire, concise et persuasive mettant en avant la proposition de valeur de votre entreprise.", kpi: "PITCH DECK PROFESSIONNEL\nCLARTÉ DU MESSAGE\nFEEDBACK POSITIF DES INVESTISSEURS" },
    { title: "Identification des Investisseurs Cibles", definition: "Sélection des investisseurs potentiels les plus pertinents pour le projet.", subtitle: "Permet de concentrer les efforts sur les investisseurs les plus susceptibles d'être intéressés.", action: "Recherchez et listez les investisseurs potentiels alignés avec votre secteur, votre stade de développement et vos besoins financiers.", kpi: "LISTE D'INVESTISSEURS POTENTIELS\nTAUX DE RÉPONSE AUX SOLLICITATIONS\nRENCONTRES PROGRAMMÉES" },
    { title: "Réseautage", definition: "Construction et entretien de relations avec des acteurs clés du secteur.", subtitle: "Le réseautage ouvre des opportunités de financement et de partenariats stratégiques.", action: "Participez à des événements, rejoignez des associations et utilisez les réseaux sociaux pour établir des contacts avec des investisseurs.", kpi: "NOMBRE DE CONTACTS ÉTABLIS\nINVITATIONS À DES ÉVÉNEMENTS\nINTRODUCTION À DES INVESTISSEURS" },
    { title: "Due Diligence Préparatoire", definition: "Préparation des documents et informations nécessaires pour l'évaluation par les investisseurs.", subtitle: "Accélère le processus de levée de fonds et démontre votre professionnalisme.", action: "Rassemblez tous les documents financiers, juridiques et opérationnels que les investisseurs pourraient demander.", kpi: "DOCUMENTS À JOUR\nRÉPONSES RAPIDES AUX DEMANDES\nAUCUN RETARD DANS LE PROCESSUS" },
    { title: "Valorisation de l'Entreprise", definition: "Estimation de la valeur financière actuelle de l'entreprise.", subtitle: "Une valorisation réaliste facilite les négociations et évite les désaccords avec les investisseurs.", action: "Utilisez des méthodes de valorisation appropriées pour déterminer une valeur réaliste de votre entreprise.", kpi: "MÉTHODOLOGIE DE VALORISATION CLAIRE\nACCEPTATION PAR LES INVESTISSEURS\nÉCART MINIMAL ENTRE ATTENTES" },
    { title: "Term Sheet", definition: "Document résumant les conditions principales de l'investissement proposé.", subtitle: "Clarifie les termes de l'accord et sert de base pour les négociations finales.", action: "Préparez un document résumant les termes et conditions proposés pour l'investissement.", kpi: "TERM SHEET RÉDIGÉ\nCONDITIONS FAVORABLES\nACCORD DES PARTIES" },
    { title: "Choix du Type de Financement", definition: "Décision entre dettes, capitaux propres ou autres instruments financiers.", subtitle: "Le type de financement choisi affecte la structure du capital et les obligations futures.", action: "Évaluez les avantages et inconvénients des différentes options (dettes, capitaux propres, obligations convertibles, etc.).", kpi: "ANALYSE DES OPTIONS RÉALISÉE\nTYPE DE FINANCEMENT ADAPTÉ\nSTRUCTURE DE CAPITAL OPTIMISÉE" },
    { title: "Timing de la Levée de Fonds", definition: "Choix du moment optimal pour lancer le processus de fundraising.", subtitle: "Un bon timing maximise les chances de succès et peut améliorer les conditions obtenues.", action: "Choisissez le moment optimal pour lancer votre levée de fonds en fonction de vos besoins financiers et des conditions du marché.", kpi: "CALENDRIER PLANIFIÉ\nOBJECTIFS ALIGNÉS AVEC LES BESOINS\nLEVÉE RÉALISÉE AU MOMENT OPPORTUN" },
    { title: "Projection Financière", definition: "Prévisions financières montrant le potentiel de croissance de l'entreprise.", subtitle: "Les projections convaincantes démontrent aux investisseurs la viabilité et l'attractivité du projet.", action: "Créez des prévisions financières détaillées sur 3 à 5 ans, incluant les hypothèses sous-jacentes.", kpi: "MODÈLES FINANCIERS SOLIDES\nHYPOTHÈSES RÉALISTES\nVALIDATION PAR DES TIERS" },
    { title: "Investisseurs Internationaux", definition: "Recherche et engagement d'investisseurs situés à l'étranger.", subtitle: "Ouvre des opportunités de financement supplémentaires et peut apporter une expertise internationale.", action: "Identifiez et engagez des investisseurs potentiels à l'étranger, en adaptant votre pitch aux spécificités culturelles.", kpi: "PRÉSENCE SUR LES MARCHÉS ÉTRANGERS\nRELATIONS ÉTABLIES\nFONDS LEVÉS À L'INTERNATIONAL" },
    { title: "Négociation avec les Investisseurs", definition: "Processus de discussion pour parvenir à un accord sur les termes de l'investissement.", subtitle: "Une négociation réussie aboutit à des conditions mutuellement bénéfiques.", action: "Engagez des discussions ouvertes avec les investisseurs pour parvenir à un accord mutuellement bénéfique.", kpi: "CONDITIONS ACCEPTÉES\nSATISFACTION DES DEUX PARTIES\nDÉLAI DE NÉGOCIATION RÉDUIT" },
    { title: "Dilution du Capital", definition: "Réduction du pourcentage de propriété des actionnaires existants après l'émission de nouvelles actions.", subtitle: "Comprendre la dilution aide à prendre des décisions éclairées sur les conditions d'investissement.", action: "Calculez l'impact de la levée de fonds sur la participation des actionnaires existants et communiquez-le clairement.", kpi: "CALCUL DE LA DILUTION\nACCEPTATION PAR LES ACTIONNAIRES\nSTRATÉGIE POUR MINIMISER L'IMPACT" },
    { title: "Alignement des Intérêts", definition: "Assurer que les objectifs des fondateurs et des investisseurs sont compatibles.", subtitle: "Un alignement solide favorise une collaboration fructueuse à long terme.", action: "Discutez des objectifs à long terme et des attentes avec les investisseurs pour garantir une vision commune.", kpi: "OBJECTIFS PARTAGÉS\nCOMMUNICATION TRANSPARENTE\nRELATION DE CONFIANCE ÉTABLIE" },
    { title: "Capital Risque (VC)", definition: "Financement par des fonds spécialisés investissant dans des startups à fort potentiel.", subtitle: "Les VC peuvent apporter des capitaux importants et un soutien stratégique.", action: "Préparez-vous aux exigences spécifiques des VC, y compris une diligence accrue et des attentes de rendement élevées.", kpi: "INTÉRÊT DES VC SUSCITÉ\nTERMES FAVORABLES OBTENUS\nSOUTIEN AU-DELÀ DU FINANCEMENT" },
    { title: "Financement Participatif (Crowdfunding)", definition: "Levée de fonds auprès d'un grand nombre de personnes via des plateformes en ligne.", subtitle: "Permet d'accéder à des fonds tout en créant une communauté autour du projet.", action: "Choisissez une plateforme adaptée, préparez une présentation attrayante et engagez votre réseau pour soutenir la campagne.", kpi: "CAMPAGNE LANCÉE\nOBJECTIF DE FINANCEMENT ATTEINT\nNOMBRE DE CONTRIBUTEURS ÉLEVÉ" },
    { title: "Subventions et Aides Publiques", definition: "Obtention de financements non dilutifs provenant de programmes gouvernementaux.", subtitle: "Réduit le besoin de capitaux propres et peut apporter une validation supplémentaire du projet.", action: "Identifiez les programmes gouvernementaux pertinents, préparez les dossiers de candidature et respectez les critères d'éligibilité.", kpi: "SUBVENTIONS OBTENUES\nMONTANT TOTAL DES AIDES\nRESPECT DES CONDITIONS D'ÉLIGIBILITÉ" },
    { title: "Confidentialité", definition: "Protection des informations sensibles lors du partage avec des investisseurs potentiels.", subtitle: "Évite la divulgation non autorisée d'informations stratégiques ou propriétaires.", action: "Faites signer des accords de confidentialité (NDA), contrôlez les documents partagés et sensibilisez votre équipe.", kpi: "NDA SIGNÉS\nCONTRÔLE DES DOCUMENTS PARTAGÉS\nAUCUNE FUITE D'INFORMATION" },
    { title: "Syndication d'Investisseurs", definition: "Collaboration entre plusieurs investisseurs pour financer un projet.", subtitle: "Augmente le montant levé et diversifie les sources de financement.", action: "Encouragez les investisseurs à collaborer pour financer votre projet, facilitant ainsi la levée de fonds.", kpi: "SYNDICAT FORMÉ\nPARTAGE DES RISQUES\nRELATIONS RENFORCÉES ENTRE INVESTISSEURS" },
    { title: "Exit Strategy (Stratégie de Sortie)", definition: "Plan pour permettre aux investisseurs de réaliser un retour sur investissement.", subtitle: "Les investisseurs sont plus enclins à investir s'ils voient une voie claire vers la liquidation de leur investissement.", action: "Planifiez les options potentielles (IPO, acquisition, rachat des actions) pour permettre aux investisseurs de réaliser leur investissement.", kpi: "STRATÉGIE DE SORTIE DÉFINIE\nACCEPTATION PAR LES INVESTISSEURS\nALIGNEMENT AVEC LES OBJECTIFS DE L'ENTREPRISE" },
    { title: "Réussite de la Levée de Fonds", definition: "Achèvement avec succès du processus de fundraising selon les objectifs fixés.", subtitle: "Fournit les ressources nécessaires pour développer l'entreprise et atteindre les objectifs stratégiques.", action: "Concluez les accords, recevez les fonds et remerciez les investisseurs, en préparant la prochaine étape de développement.", kpi: "MONTANT VISÉ ATTEINT\nCONDITIONS FAVORABLES\nINVESTISSEURS SATISFAITS" },
  ],
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceRoleKey);

    const results: string[] = [];

    // Step 1: Update pillars
    for (const p of PILLAR_UPDATES) {
      const { error } = await supabase
        .from("pillars")
        .update({ name: p.name, slug: p.slug, icon_name: p.icon_name, description: p.description, sort_order: p.sort_order })
        .eq("id", p.id);
      if (error) results.push(`Pillar update error ${p.slug}: ${error.message}`);
      else results.push(`Pillar updated: ${p.slug}`);
    }

    // Step 2: Delete existing cards and progress
    const { error: progressErr } = await supabase.from("user_card_progress").delete().neq("id", "00000000-0000-0000-0000-000000000000");
    results.push(progressErr ? `Progress delete error: ${progressErr.message}` : "Progress deleted");

    const { error: cardsErr } = await supabase.from("cards").delete().neq("id", "00000000-0000-0000-0000-000000000000");
    results.push(cardsErr ? `Cards delete error: ${cardsErr.message}` : "Cards deleted");

    // Step 3: Insert all 200 cards
    let totalInserted = 0;
    for (const [pillarKey, cards] of Object.entries(ALL_CARDS)) {
      const pillarId = PILLAR_IDS[pillarKey as keyof typeof PILLAR_IDS];
      if (!pillarId) {
        results.push(`Unknown pillar: ${pillarKey}`);
        continue;
      }

      const rows = cards.map((card, i) => ({
        pillar_id: pillarId,
        title: card.title,
        definition: card.definition,
        subtitle: card.subtitle,
        action: card.action,
        kpi: card.kpi,
        phase: getPhase(i),
        sort_order: i,
      }));

      const { error } = await supabase.from("cards").insert(rows);
      if (error) {
        results.push(`Insert error for ${pillarKey}: ${error.message}`);
      } else {
        totalInserted += rows.length;
        results.push(`Inserted ${rows.length} cards for ${pillarKey}`);
      }
    }

    results.push(`Total cards inserted: ${totalInserted}`);

    return new Response(JSON.stringify({ success: true, results }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
